import { useState } from "react";
import { retryConsultationSummary } from "../services/api";

export default function PatientSummary({ record, onUpdate }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  async function retry() {
    setBusy(true);
    setError("");
    try {
      const result = await retryConsultationSummary(record.id);
      onUpdate?.(result);
      if (result.summary_source === "basic") setError(result.summary_error || "Ollama could not prepare the summary. Your original responses and basic summary are saved.");
    } catch (failure) {
      setError(failure.message);
    } finally {
      setBusy(false);
    }
  }
  return (
    <section className="patient-summary" aria-label="Patient summary" aria-live="polite">
      <h2>Patient-reported summary</h2>
      <p className="muted">{record.summary_source === "ollama" ? "AI-generated with Ollama · Requires healthcare professional review" : "Basic response summary · Not generated by AI"}</p>
      <p className="summary-text">{record.summary || "No summary is available for this submission."}</p>
      {record.summary_error && !error && <p role="status">{record.summary_error}</p>}
      {record.summary_source !== "ollama" && record.id && (
        <>
          <p>AI analysis is not available for this summary yet. No possible conditions have been generated.</p>
          <button type="button" className="button button-outline" disabled={busy || record.summary_source === "generating"} onClick={retry}>
            {busy || record.summary_source === "generating" ? "Preparing AI summary..." : "Try AI summary"}
          </button>
        </>
      )}
      {error && <p className="error" role="alert">{error}</p>}
    </section>
  );
}
