import { test, expect } from "@playwright/test";

const summary = "The patient reports a headache starting today and a penicillin allergy.\n\nPossible conditions to discuss — not diagnoses\nTension-type headache may be one possibility, but a clinician must assess this.\n\nThis summary is based only on the patient's responses and requires healthcare professional review.";
const record = { id: "consultation", symptoms: ["Headache"], duration: "Today", impact: "Some activities are difficult", history: "Penicillin allergy", medicines: "", notes: "", summary, summary_source: "ollama", summary_model: "test-model", appointment: null, images: [], offers: [], patient: { name: "Example Patient", email: "patient@example.com" }, created_at: "2026-09-30 10:00:00" };

test("one submitted summary is shown to the patient, after refresh, and to admin", async ({ page, context }) => {
  let submitted = false;
  let creates = 0;
  await page.route("**/auth/me", route => route.fulfill({ json: { user: { id: "patient", name: "Example Patient", email: "patient@example.com", role: "patient" } } }));
  await page.route("**/consultations/mine/latest", route => route.fulfill({ json: submitted ? record : null }));
  await page.route("**/consultations", route => {
    creates += 1;
    submitted = true;
    expect(route.request().postDataJSON().history).toBe("Penicillin allergy");
    return route.fulfill({ json: { ...record, status: "created" } });
  });
  await page.goto("/#/consultation");
  await page.getByLabel("Headache", { exact: true }).check();
  await page.getByLabel("When did this start?").selectOption("Today");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByLabel("How much is this affecting your day?").selectOption("Some activities are difficult");
  await page.getByLabel(/Existing conditions/).fill("Penicillin allergy");
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await page.getByRole("link", { name: "Review information" }).click();
  await page.getByRole("checkbox").check();
  await page.getByRole("button", { name: "Submit questionnaire" }).click();
  await expect(page.getByRole("heading", { name: "Your submitted pre-consultation" })).toBeVisible();
  await expect(page.locator(".summary-text")).toHaveText(summary);
  await expect(page.getByText("Penicillin allergy", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.locator(".summary-text")).toHaveText(summary);
  expect(creates).toBe(1);
  const admin = await context.newPage();
  await admin.route("**/auth/me", route => route.fulfill({ json: { user: { id: "admin", name: "Admin", email: "admin@example.com", role: "admin" } } }));
  await admin.route("**/consultations/mine/latest", route => route.fulfill({ json: null }));
  await admin.route("**/admin/consultations", route => route.fulfill({ json: [record] }));
  await admin.goto("/#/admin");
  await expect(admin.locator(".summary-text")).toHaveText(summary);
  await expect(admin.getByText("Penicillin allergy", { exact: true })).toBeVisible();
});

test("unavailable AI is labelled honestly and retry updates the saved summary", async ({ page }) => {
  await page.route("**/auth/me", route => route.fulfill({ json: { user: { id: "patient", name: "Example Patient", email: "patient@example.com", role: "patient" } } }));
  await page.route("**/consultations/mine/latest", route => route.fulfill({ json: { ...record, summary: "The patient reports Headache. Clinical review is needed.", summary_source: "basic" } }));
  await page.route("**/consultations/consultation/summary", route => route.fulfill({ json: record }));
  await page.goto("/#/review");
  await expect(page.getByText("Basic response summary · Not generated by AI")).toBeVisible();
  await page.getByRole("button", { name: "Try AI summary" }).click();
  await expect(page.locator(".summary-text")).toHaveText(summary);
  await expect(page.getByRole("button", { name: "Try AI summary" })).toHaveCount(0);
});

test("a stopped Ollama server gives actionable feedback", async ({ page }) => {
  await page.route("**/auth/me", route => route.fulfill({ json: { user: { id: "patient", name: "Example Patient", email: "patient@example.com", role: "patient" } } }));
  await page.route("**/consultations/mine/latest", route => route.fulfill({ json: { ...record, summary_source: "basic" } }));
  const error = "Ollama is not running or cannot be reached. Open Ollama or run ollama serve, then try again.";
  await page.route("**/consultations/consultation/summary", route => route.fulfill({ json: { ...record, summary_source: "basic", summary_error: error } }));
  await page.goto("/#/review");
  await page.getByRole("button", { name: "Try AI summary" }).click();
  await expect(page.getByRole("alert")).toHaveText(error);
});
